export const LEVEL_TITLES = [
  "Cadet", "Ensign", "Pilot", "Captain", "Commander",
  "Admiral", "Star Lord", "Galaxy Hero", "Cosmic Legend", "Supreme Explorer",
];
export const LEVEL_THRESHOLDS = [0, 30, 75, 140, 230, 350, 500, 700, 950, 1250];
export const PARENT_PIN = "1234";

export const INITIAL_STATE = {
  parentPin: "1234",
  members: [
    { id: "p1", name: "Mom", avatar: "👩‍🚀", role: "parent", xp: 0, tokens: 0, level: 1, streak: 0 },
    { id: "p2", name: "Dad", avatar: "🧑‍🚀", role: "parent", xp: 0, tokens: 0, level: 1, streak: 0 },
    { id: "k1", name: "Kid 1", avatar: "🚀", role: "kid", xp: 0, tokens: 0, level: 1, streak: 0 },
    { id: "k2", name: "Kid 2", avatar: "🛸", role: "kid", xp: 0, tokens: 0, level: 1, streak: 0 },
  ],
  quests: [
    { id: "d1", title: "Make Your Bed", description: "Sheets pulled up, pillow in place", type: "daily", xpReward: 5, tokenReward: 2, requiresApproval: true, assignedTo: null, isActive: true, audience: "kids" },
    { id: "d2", title: "Brush Teeth (Morning)", description: "2 full minutes!", type: "daily", xpReward: 5, tokenReward: 2, requiresApproval: false, assignedTo: null, isActive: true, audience: "kids" },
    { id: "d3", title: "Brush Teeth (Night)", description: "Don't forget to floss", type: "daily", xpReward: 5, tokenReward: 2, requiresApproval: false, assignedTo: null, isActive: true, audience: "kids" },
    { id: "d4", title: "Pick Up Toys", description: "Everything back where it belongs", type: "daily", xpReward: 8, tokenReward: 3, requiresApproval: true, assignedTo: null, isActive: true, audience: "kids" },
    { id: "d5", title: "Feed the Pet", description: "Fresh food and water", type: "daily", xpReward: 5, tokenReward: 2, requiresApproval: false, assignedTo: null, isActive: true, audience: "all" },
    { id: "d6", title: "Tidy the Living Room", description: "Pillows straight, blankets folded, floor clear", type: "daily", xpReward: 8, tokenReward: 3, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "d7", title: "Tidy the Family Room", description: "Put away games, remotes in place, no clutter", type: "daily", xpReward: 8, tokenReward: 3, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "d8", title: "Wipe Kitchen Table", description: "After a meal — spray and wipe, no crumbs", type: "daily", xpReward: 5, tokenReward: 2, requiresApproval: false, assignedTo: null, isActive: true, audience: "all" },
    { id: "d9", title: "Take Out Trash", description: "Kitchen trash to the bin outside", type: "daily", xpReward: 5, tokenReward: 2, requiresApproval: false, assignedTo: null, isActive: true, audience: "all" },
    { id: "d10", title: "Put Away Dishes", description: "Unload the dishwasher or dry rack", type: "daily", xpReward: 8, tokenReward: 3, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "w1", title: "Clean Your Room", description: "Full deep clean — floor, desk, closet", type: "weekly", xpReward: 20, tokenReward: 10, requiresApproval: true, assignedTo: null, isActive: true, audience: "kids" },
    { id: "w2", title: "Help With Yard Work", description: "30 minutes of outdoor help", type: "weekly", xpReward: 25, tokenReward: 12, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "w3", title: "Read for 1 Hour", description: "Any book, total across the week", type: "weekly", xpReward: 15, tokenReward: 8, requiresApproval: true, assignedTo: null, isActive: true, audience: "kids" },
    { id: "w4", title: "Clean a Bathroom", description: "Toilet, sink, mirror, floor — the whole deal", type: "weekly", xpReward: 25, tokenReward: 12, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "w5", title: "Vacuum a Room", description: "Pick a room, move furniture, get the edges", type: "weekly", xpReward: 15, tokenReward: 8, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "w6", title: "Mop the Kitchen Floor", description: "Sweep first, then mop the whole floor", type: "weekly", xpReward: 20, tokenReward: 10, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "w7", title: "Do a Load of Laundry", description: "Wash, dry, fold, AND put away", type: "weekly", xpReward: 25, tokenReward: 12, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "w8", title: "Dust the House", description: "Shelves, windowsills, and surfaces in 2+ rooms", type: "weekly", xpReward: 15, tokenReward: 8, requiresApproval: true, assignedTo: null, isActive: true, audience: "all" },
    { id: "ad1", title: "Cook Dinner", description: "Plan, prep, cook, and serve a full meal", type: "daily", xpReward: 15, tokenReward: 5, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "ad2", title: "Pack Lunches", description: "Lunches prepped and packed for tomorrow", type: "daily", xpReward: 8, tokenReward: 3, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "ad3", title: "Run the Dishwasher", description: "Load it up, run it, put away when done", type: "daily", xpReward: 8, tokenReward: 3, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "ad4", title: "Wipe Down Kitchen", description: "Counters, stovetop, and sink — full wipe", type: "daily", xpReward: 8, tokenReward: 3, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "ad5", title: "Sort the Mail", description: "Open, file, recycle — no pile-ups", type: "daily", xpReward: 5, tokenReward: 2, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "aw1", title: "Mow the Lawn", description: "Full mow, trim edges, blow off driveway", type: "weekly", xpReward: 30, tokenReward: 15, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "aw2", title: "Grocery Shopping", description: "Plan the list, shop, and put everything away", type: "weekly", xpReward: 25, tokenReward: 12, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "aw3", title: "Deep Clean Kitchen", description: "Appliances, inside fridge, scrub sink", type: "weekly", xpReward: 30, tokenReward: 15, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "aw4", title: "Meal Prep Sunday", description: "Prep ingredients or full meals for the week", type: "weekly", xpReward: 30, tokenReward: 15, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "aw5", title: "Pay Bills / Budget Check", description: "Review finances, pay due bills, update budget", type: "weekly", xpReward: 20, tokenReward: 10, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "aw6", title: "Organize a Closet or Drawer", description: "Pick one, purge, reorganize", type: "weekly", xpReward: 20, tokenReward: 10, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
    { id: "aw7", title: "Car Maintenance", description: "Wash, vacuum, check fluids, or tire pressure", type: "weekly", xpReward: 20, tokenReward: 10, requiresApproval: false, assignedTo: null, isActive: true, audience: "adults" },
  ],
  mysteryPool: [
    { title: "Surprise Sweep", description: "Sweep the kitchen floor without being asked", xpReward: 12, tokenReward: 6 },
    { title: "Kindness Mission", description: "Do something nice for your sibling", xpReward: 10, tokenReward: 5 },
    { title: "Laundry Cadet", description: "Help fold one load of laundry", xpReward: 15, tokenReward: 7 },
    { title: "Dish Duty", description: "Help load or unload the dishwasher", xpReward: 12, tokenReward: 6 },
    { title: "Weed Warrior", description: "Pull 20 weeds from the garden", xpReward: 15, tokenReward: 8 },
  ],
  rewards: [
    { id: "r1", title: "Pick Tonight's Dessert", tokenCost: 10, isAvailable: true },
    { id: "r2", title: "30 Min Extra Screen Time", tokenCost: 20, isAvailable: true },
    { id: "r3", title: "Pick Family Movie", tokenCost: 50, isAvailable: true },
    { id: "r4", title: "Skip One Chore (Free Pass)", tokenCost: 35, isAvailable: true },
    { id: "r5", title: "Special Outing of Your Choice", tokenCost: 100, isAvailable: true },
  ],
  adultRewards: [
    { id: "ar1", title: "Sleep In Saturday", tokenCost: 30, isAvailable: true },
    { id: "ar2", title: "Solo Coffee Shop Trip", tokenCost: 20, isAvailable: true },
    { id: "ar3", title: "Pick the Takeout Restaurant", tokenCost: 15, isAvailable: true },
    { id: "ar4", title: "Guilt-Free Gaming/Hobby Hour", tokenCost: 25, isAvailable: true },
    { id: "ar5", title: "Skip Cooking — Order In", tokenCost: 40, isAvailable: true },
    { id: "ar6", title: "Date Night Out", tokenCost: 80, isAvailable: true },
  ],
  coopMission: {
    title: "Asteroid Belt Challenge",
    description: "Kids earn 80 XP combined this week!",
    targetXp: 80,
    currentXp: 0,
    reward: "Family Ice Cream Trip 🍦",
    weekStart: new Date().toISOString(),
  },
  adultCoopMission: {
    title: "Home Base Blitz",
    description: "Parents earn 100 XP combined this week!",
    targetXp: 100,
    currentXp: 0,
    reward: "Date Night Out 🌙",
    weekStart: new Date().toISOString(),
  },
  longTermMission: {
    title: "Yes Day",
    description: "Kids earn 1000 XP total to unlock a full Yes Day — a whole day where you pick everything!",
    targetXp: 1000,
    currentXp: 0,
    reward: "Yes Day 🎉",
  },
  completions: [],
  pendingRewards: [],
  todayMystery: null,
  activityLog: [],
  weekStart: new Date().toISOString(),
};
